Repository nextcloud-libraries/webpack-vue-config, pull requests merged in 2021-11, with the labels that each got.

#230 Add style testing
  .gitignore
  index.js
  rules.js
  tests/.eslintrc.js
  tests/babel.config.js
  tests/js/webpack-vue-config-test-main.js
  tests/js/webpack-vue-config-test-main.js.map
  tests/src/main.js
  tests/src/views/MainView.vue
  tests/stylelint.config.js
  tests/webpack.js
  webpack.js
Labels: enhancement

#233 Change webpack version in peerDep to match devDep
  package.json
Labels: dependencies

#241 Update npm and node engines versions
  package.json
Labels: dependencies

#246 Fix HMR
  package.json
  webpack.js
Labels: bug

#242 Move stylelint to 14
  .github/workflows/npm-test.yml
  package-lock.json
  package.json
  tests/package-lock.json
  tests/package.json
Labels: dependencies
