Repository nextcloud-libraries/webpack-vue-config, pull requests merged in 2022-01, with the labels that each got.

#268 Change webpack config for more platform independency
  README.md
  index.js
  webpack.config.js
Labels: documentation, dependencies

#269 Bump dependencies
  package-lock.json
  package.json
Labels: bug, dependencies

#273 Bump sass to 1.47.0
  package-lock.json
  package.json
Labels: dependencies

#275 Unpin webpack version
  package-lock.json
  package.json
Labels: dependencies

#274 Eslint 8
  package-lock.json
  package.json
  tests/package-lock.json
  tests/package.json
  tests/src/views/MainView.vue
Labels: dependencies

#279 Fix devDependencies
  package-lock.json
  package.json
Labels: bug, backport-request

#286 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
